#!/usr/bin/env bash
# scripts/bench-hold.sh — Hold-mode (press-and-hold) release-to-text baseline.
#
# `scripts/bench-latency.sh` measures ASR in isolation and
# `scripts/bench-end-to-end.sh` measures the Tap path, where Silero VAD owns
# the endpoint. Neither covers Hold, whose endpoint is the hotkey release.
# This harness plays each fixture through the loopback device, releases at the
# predicted instant of the fixture's last audible sample, and records
# release-to-transcript-ready in `dur_end_to_end_ms`.
#
# Requires a duplex Core Audio loopback named "BlackHole 2ch" (override with
# DEVICE) at the fixture sample rate, and the fixtures generated by
# scripts/bench-latency.sh.
#
# HOLD_WINDOWS selects what the Hold path does during the hold: `off` is the
# original serial behaviour (nothing decodes until release), `MIN,MAX` cuts
# windows at pauses and decodes them in the background (ADR-0032). Run it both
# ways to get the before/after columns from one sitting.
#
# The `multipause` fixture is a long utterance with explicit 800 ms gaps, which
# is where window cutting is supposed to pay off most. It is generated here
# rather than in bench-latency.sh because only Hold uses it.
#
# Outputs:
#   bench/hold.log            — every repetition's phase_timer line.
#   bench/hold.csv (or $OUT_CSV)
#
# Usage:
#   scripts/bench-hold.sh
#   REPS=30 BACKEND=coreml-unified scripts/bench-hold.sh
#   HOLD_WINDOWS=off OUT_CSV=bench/hold-serial.csv scripts/bench-hold.sh

set -euo pipefail

cd "$(dirname "$0")/.."

REPS="${REPS:-30}"
WARMUP_REPS="${WARMUP_REPS:-2}"
SAMPLE_RATE="${SAMPLE_RATE:-48000}"
DEVICE="${DEVICE:-BlackHole 2ch}"
BACKEND="${BACKEND:-coreml-unified}"
HOLD_WINDOWS="${HOLD_WINDOWS:-3,6}"
LENGTHS=(1 3 5 10 20)
WAV_DIR="bench/audio"
RAW_LOG="${RAW_LOG:-bench/hold.log}"
OUT_CSV="${OUT_CSV:-bench/hold.csv}"
MULTIPAUSE_WAV="$WAV_DIR/multipause_${SAMPLE_RATE}.wav"

command -v uv >/dev/null || { echo "missing \`uv\` (brew install uv)"; exit 1; }
command -v say >/dev/null || { echo "missing macOS \`say\`"; exit 1; }
command -v afconvert >/dev/null || { echo "missing macOS \`afconvert\`"; exit 1; }

for len in "${LENGTHS[@]}"; do
    wav="$WAV_DIR/${len}s_${SAMPLE_RATE}.wav"
    [[ -f "$wav" ]] || {
        echo "missing $wav — run scripts/bench-latency.sh first to generate fixtures" >&2
        exit 1
    }
done

# Four clauses separated by explicit 800 ms gaps: long enough for Silero to
# confirm a pause, short enough to be ordinary speech rather than a new
# utterance. `say` honours the inline [[slnc N]] command in milliseconds.
if [[ ! -f "$MULTIPAUSE_WAV" ]]; then
    echo "Generating $MULTIPAUSE_WAV (${SAMPLE_RATE} Hz mono PCM16)…"
    aiff="$WAV_DIR/multipause.aiff"
    say -o "$aiff" \
        "The latency benchmark drives the recognizer with audio of fixed lengths. \
[[slnc 800]] It records timing for thirty iterations and aggregates the result. \
[[slnc 800]] Then it writes the percentiles to a comma separated file. \
[[slnc 800]] That file is included in the architecture decision record."
    afconvert -f WAVE -d "LEI16@${SAMPLE_RATE}" -c 1 "$aiff" "$MULTIPAUSE_WAV"
    rm "$aiff"
fi

if [[ "$BACKEND" == "coreml-unified" ]]; then
    echo "Building native Core ML worker…"
    scripts/build-coreml-worker.sh
fi
echo "Building bench_e2e (release)…"
cargo build --release --bin bench_e2e 2>&1 | tail -3

: > "$RAW_LOG"
for len in "${LENGTHS[@]}"; do
    wav="$WAV_DIR/${len}s_${SAMPLE_RATE}.wav"
    echo "Hold-benching $wav (backend=$BACKEND, windows=$HOLD_WINDOWS, warmup=$WARMUP_REPS, reps=$REPS)…"
    ./target/release/bench_e2e \
        --backend "$BACKEND" --mode hold --wav "$wav" --device "$DEVICE" \
        --hold-windows "$HOLD_WINDOWS" \
        --reps "$REPS" --warmup-reps "$WARMUP_REPS" \
        2>>"$RAW_LOG" \
        || echo "  ↑ hold bench failed for $wav (see $RAW_LOG)"
done

uv run --quiet scripts/bench-aggregate.py --log "$RAW_LOG" --out "$OUT_CSV" --metric end-to-end

# The multipause fixture is aggregated on its own: bench-aggregate.py buckets by
# measured duration to the nearest of {1,3,5,10,20}s, and this one is not one of
# those lengths.
MULTIPAUSE_LOG="${RAW_LOG%.log}-multipause.log"
MULTIPAUSE_CSV="${OUT_CSV%.csv}-multipause.csv"
echo "Hold-benching $MULTIPAUSE_WAV (backend=$BACKEND, windows=$HOLD_WINDOWS)…"
: > "$MULTIPAUSE_LOG"
./target/release/bench_e2e \
    --backend "$BACKEND" --mode hold --wav "$MULTIPAUSE_WAV" --device "$DEVICE" \
    --hold-windows "$HOLD_WINDOWS" \
    --reps "$REPS" --warmup-reps "$WARMUP_REPS" \
    2>>"$MULTIPAUSE_LOG" \
    || echo "  ↑ hold bench failed for $MULTIPAUSE_WAV (see $MULTIPAUSE_LOG)"
uv run --quiet scripts/bench-aggregate.py \
    --log "$MULTIPAUSE_LOG" --out "$MULTIPAUSE_CSV" --metric end-to-end

echo
echo "Wrote $OUT_CSV and $MULTIPAUSE_CSV"
cat "$OUT_CSV"
cat "$MULTIPAUSE_CSV"
