#!/usr/bin/env bash
# scripts/bench-hold.sh — Hold-mode (press-and-hold) release-to-text baseline.
#
# `scripts/bench-latency.sh` measures ASR in isolation and
# `scripts/bench-end-to-end.sh` measures the Tap path, where Silero VAD owns
# the endpoint. Neither covers Hold, whose endpoint is the hotkey release.
# This harness plays each fixture through the loopback device, releases at the
# predicted instant of the fixture's last audible sample, and records
# release-to-transcript-ready in `dur_end_to_end_ms`.
#
# Requires a duplex Core Audio loopback named "BlackHole 2ch" (override with
# DEVICE) at the fixture sample rate, and the fixtures generated by
# scripts/bench-latency.sh.
#
# Outputs:
#   bench/hold.log            — every repetition's phase_timer line.
#   bench/hold.csv (or $OUT_CSV)
#
# Usage:
#   scripts/bench-hold.sh
#   REPS=30 BACKEND=coreml-unified scripts/bench-hold.sh

set -euo pipefail

cd "$(dirname "$0")/.."

REPS="${REPS:-30}"
WARMUP_REPS="${WARMUP_REPS:-2}"
SAMPLE_RATE="${SAMPLE_RATE:-48000}"
DEVICE="${DEVICE:-BlackHole 2ch}"
BACKEND="${BACKEND:-coreml-unified}"
LENGTHS=(1 3 5 10 20)
WAV_DIR="bench/audio"
RAW_LOG="bench/hold.log"
OUT_CSV="${OUT_CSV:-bench/hold.csv}"

command -v uv >/dev/null || { echo "missing \`uv\` (brew install uv)"; exit 1; }

for len in "${LENGTHS[@]}"; do
    wav="$WAV_DIR/${len}s_${SAMPLE_RATE}.wav"
    [[ -f "$wav" ]] || {
        echo "missing $wav — run scripts/bench-latency.sh first to generate fixtures" >&2
        exit 1
    }
done

if [[ "$BACKEND" == "coreml-unified" ]]; then
    echo "Building native Core ML worker…"
    scripts/build-coreml-worker.sh
fi
echo "Building bench_e2e (release)…"
cargo build --release --bin bench_e2e 2>&1 | tail -3

: > "$RAW_LOG"
for len in "${LENGTHS[@]}"; do
    wav="$WAV_DIR/${len}s_${SAMPLE_RATE}.wav"
    echo "Hold-benching $wav (backend=$BACKEND, warmup=$WARMUP_REPS, reps=$REPS)…"
    ./target/release/bench_e2e \
        --backend "$BACKEND" --mode hold --wav "$wav" --device "$DEVICE" \
        --reps "$REPS" --warmup-reps "$WARMUP_REPS" \
        2>>"$RAW_LOG" \
        || echo "  ↑ hold bench failed for $wav (see $RAW_LOG)"
done

uv run --quiet scripts/bench-aggregate.py --log "$RAW_LOG" --out "$OUT_CSV" --metric end-to-end

echo
echo "Wrote $OUT_CSV"
cat "$OUT_CSV"
