//! Shared WAV reader for the headless bench binaries.
//!
//! Lives in the library rather than in `bench_asr` so `asr_diff` can
//! decode the same fixtures without a second, subtly-different parser
//! (a transcript-diff harness that disagrees with the latency harness
//! about how to fold stereo to mono would report phantom regressions).

use std::fs::File;
use std::io::BufReader;
use std::path::Path;

/// Read a 16-bit PCM WAV (mono or stereo) into f32 samples in [-1, 1].
/// Folds multi-channel input to mono by averaging. Refuses anything other
/// than 16-bit PCM, since the bench fixtures are generated by `afconvert
/// -d LEI16@... -c 1` (single-channel little-endian 16-bit).
pub fn read_wav_mono(path: &Path) -> anyhow::Result<(Vec<f32>, u32)> {
    use std::io::Read;
    let file = File::open(path).map_err(|e| anyhow::anyhow!("opening {}: {e}", path.display()))?;
    let mut r = BufReader::new(file);

    let mut header = [0u8; 12];
    r.read_exact(&mut header)?;
    if &header[0..4] != b"RIFF" || &header[8..12] != b"WAVE" {
        anyhow::bail!("not a RIFF/WAVE file: {}", path.display());
    }

    // Cap per-chunk allocation: a bench fixture > 1 GiB indicates a
    // corrupt header (raw u32 sizes from disk are otherwise unbounded).
    const MAX_CHUNK_BYTES: usize = 1024 * 1024 * 1024;

    let mut sample_rate = 0u32;
    let mut channels = 0u16;
    let mut bits_per_sample = 0u16;
    let mut data: Vec<u8> = Vec::new();

    loop {
        let mut chunk_hdr = [0u8; 8];
        match r.read_exact(&mut chunk_hdr) {
            Ok(()) => {}
            Err(e) if e.kind() == std::io::ErrorKind::UnexpectedEof => break,
            Err(e) => return Err(e.into()),
        }
        let id = &chunk_hdr[0..4];
        let size =
            u32::from_le_bytes([chunk_hdr[4], chunk_hdr[5], chunk_hdr[6], chunk_hdr[7]]) as usize;
        if size > MAX_CHUNK_BYTES {
            anyhow::bail!(
                "WAV chunk size {size} exceeds {MAX_CHUNK_BYTES} byte cap (corrupt header?)"
            );
        }

        if id == b"fmt " {
            let mut fmt = vec![0u8; size];
            r.read_exact(&mut fmt)?;
            // The canonical PCM `fmt ` chunk is 16 bytes and we index
            // through byte 15. A truncated or malformed chunk would
            // panic on the slice indexing below; report it instead.
            if fmt.len() < 16 {
                anyhow::bail!(
                    "malformed WAV: `fmt ` chunk is {} bytes, need at least 16",
                    fmt.len()
                );
            }
            let fmt_tag = u16::from_le_bytes([fmt[0], fmt[1]]);
            if fmt_tag != 1 {
                anyhow::bail!("only PCM (fmt tag 1) supported, got {fmt_tag}");
            }
            channels = u16::from_le_bytes([fmt[2], fmt[3]]);
            sample_rate = u32::from_le_bytes([fmt[4], fmt[5], fmt[6], fmt[7]]);
            bits_per_sample = u16::from_le_bytes([fmt[14], fmt[15]]);
        } else if id == b"data" {
            data.resize(size, 0);
            r.read_exact(&mut data)?;
        } else {
            // Skip unknown chunks (e.g. LIST, JUNK).
            let mut skip = vec![0u8; size];
            r.read_exact(&mut skip)?;
        }

        // RIFF pads every odd-sized chunk to an even boundary. Without
        // consuming that byte, an odd chunk misaligns every subsequent
        // chunk header and the parse silently degenerates.
        if size % 2 == 1 {
            let mut pad = [0u8; 1];
            match r.read_exact(&mut pad) {
                Ok(()) => {}
                Err(e) if e.kind() == std::io::ErrorKind::UnexpectedEof => break,
                Err(e) => return Err(e.into()),
            }
        }
    }

    if bits_per_sample != 16 {
        anyhow::bail!(
            "only 16-bit PCM supported, got {bits_per_sample}-bit \
             (regenerate with `afconvert -d LEI16@RATE`)"
        );
    }
    if channels == 0 || sample_rate == 0 || data.is_empty() {
        anyhow::bail!("WAV missing fmt or data chunk");
    }

    let frame_bytes = 2 * channels as usize;
    let frames = data.len() / frame_bytes;
    let mut out = Vec::with_capacity(frames);
    for i in 0..frames {
        let frame = &data[i * frame_bytes..(i + 1) * frame_bytes];
        let mut sum = 0i32;
        for c in 0..channels as usize {
            let s = i32::from(i16::from_le_bytes([frame[2 * c], frame[2 * c + 1]]));
            sum += s;
        }
        let avg = sum as f32 / f32::from(channels);
        // Divide by 32768, not i16::MAX (32767): `i16::MIN` is -32768,
        // so scaling by MAX yields -1.00003 and breaks the documented
        // [-1, 1] range on any fixture that hits full negative scale.
        out.push(avg / 32768.0);
    }
    Ok((out, sample_rate))
}
